apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
data:
  DATABASE_URL: "postgresql://eswar:sntfsH4KseIRok6uJt8kecLmz0ikuHFE@dpg-cruv2s88fa8c73co7bhg-a.singapore-postgres.render.com/bookiedb_1h4f"