apiVersion: v1
kind: Service
metadata:
  name: book-catalog-service
spec:
  selector:
    app: book-catalog  # Ensure both pods have this label
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: book-catalog-port
    - protocol: TCP
      port: 81
      targetPort: 80  # Assuming inventory listens on the same target port
      name: inventory-port
  type: NodePort
